//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace einvoice.QRCodeReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="QRCodeReference.QREncryptServiceSoap")]
    public interface QREncryptServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QREncryptTest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string QREncryptTest();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QREncryptTest", ReplyAction="*")]
        System.Threading.Tasks.Task<string> QREncryptTestAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QREncrypt", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string QREncrypt(einvoice.QRCodeReference.QRCode qrCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QREncrypt", ReplyAction="*")]
        System.Threading.Tasks.Task<string> QREncryptAsync(einvoice.QRCodeReference.QRCode qrCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InitQRCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        einvoice.QRCodeReference.QRCode InitQRCode();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InitQRCode", ReplyAction="*")]
        System.Threading.Tasks.Task<einvoice.QRCodeReference.QRCode> InitQRCodeAsync();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class QRCode : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string invoiceNumberField;
        
        private string invoiceDateField;
        
        private string invoiceTimeField;
        
        private int salesAmountField;
        
        private int taxAmountField;
        
        private int totalAmountField;
        
        private string buyerIdentifierField;
        
        private string representIdentifierField;
        
        private string sellerIdentifierField;
        
        private int errorCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string InvoiceNumber {
            get {
                return this.invoiceNumberField;
            }
            set {
                this.invoiceNumberField = value;
                this.RaisePropertyChanged("InvoiceNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string InvoiceDate {
            get {
                return this.invoiceDateField;
            }
            set {
                this.invoiceDateField = value;
                this.RaisePropertyChanged("InvoiceDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string InvoiceTime {
            get {
                return this.invoiceTimeField;
            }
            set {
                this.invoiceTimeField = value;
                this.RaisePropertyChanged("InvoiceTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int SalesAmount {
            get {
                return this.salesAmountField;
            }
            set {
                this.salesAmountField = value;
                this.RaisePropertyChanged("SalesAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int TaxAmount {
            get {
                return this.taxAmountField;
            }
            set {
                this.taxAmountField = value;
                this.RaisePropertyChanged("TaxAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int TotalAmount {
            get {
                return this.totalAmountField;
            }
            set {
                this.totalAmountField = value;
                this.RaisePropertyChanged("TotalAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string BuyerIdentifier {
            get {
                return this.buyerIdentifierField;
            }
            set {
                this.buyerIdentifierField = value;
                this.RaisePropertyChanged("BuyerIdentifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string RepresentIdentifier {
            get {
                return this.representIdentifierField;
            }
            set {
                this.representIdentifierField = value;
                this.RaisePropertyChanged("RepresentIdentifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string SellerIdentifier {
            get {
                return this.sellerIdentifierField;
            }
            set {
                this.sellerIdentifierField = value;
                this.RaisePropertyChanged("SellerIdentifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface QREncryptServiceSoapChannel : einvoice.QRCodeReference.QREncryptServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QREncryptServiceSoapClient : System.ServiceModel.ClientBase<einvoice.QRCodeReference.QREncryptServiceSoap>, einvoice.QRCodeReference.QREncryptServiceSoap {
        
        public QREncryptServiceSoapClient() {
        }
        
        public QREncryptServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QREncryptServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QREncryptServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QREncryptServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public string QREncryptTest() {
            return base.Channel.QREncryptTest();
        }
        
        public System.Threading.Tasks.Task<string> QREncryptTestAsync() {
            return base.Channel.QREncryptTestAsync();
        }
        
        public string QREncrypt(einvoice.QRCodeReference.QRCode qrCode) {
            return base.Channel.QREncrypt(qrCode);
        }
        
        public System.Threading.Tasks.Task<string> QREncryptAsync(einvoice.QRCodeReference.QRCode qrCode) {
            return base.Channel.QREncryptAsync(qrCode);
        }
        
        public einvoice.QRCodeReference.QRCode InitQRCode() {
            return base.Channel.InitQRCode();
        }
        
        public System.Threading.Tasks.Task<einvoice.QRCodeReference.QRCode> InitQRCodeAsync() {
            return base.Channel.InitQRCodeAsync();
        }
    }
}
