// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using IOTGateway.Models;
using Microsoft.Rest;

namespace IOTGateway
{
    public partial interface IFieldGateway
    {
        /// <param name='deviceId'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<string>> ReceiveCommandByDeviceidWithOperationResponseAsync(string deviceId, CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        
        /// <param name='deviceId'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<string>> RegisterByDeviceidWithOperationResponseAsync(string deviceId, CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        
        /// <param name='telemetry'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> SendTelemetryByTelemetryWithOperationResponseAsync(TelemetryData telemetry, CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        
        /// <param name='deviceId'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> UnregisterByDeviceidWithOperationResponseAsync(string deviceId, CancellationToken cancellationToken = default(System.Threading.CancellationToken));
    }
}
