/'Design Pattern Relationships'/
@startuml Design Pattern Relationships
artifact Composite
artifact "Chain of Responsibility"
artifact Visitor
artifact Interpreter
artifact Flyweight
artifact Iterator
artifact Memento
artifact Command
artifact State
artifact Strategy
artifact Decorator
artifact Builder
artifact "Template Method"
artifact "Factory Method"
artifact "Abstract Factory"
artifact Prototype
artifact Singleton
artifact Facade
artifact Mediator
artifact Observer
artifact Proxy
artifact Bridge
artifact Adapter

Iterator -[hidden]left- Builder
[Chain of Responsibility] -up-> Composite:定義串鏈
Composite -up-> Builder:建立複合體
Composite -right-> Visitor:增添操作
Composite -left-> Decorator:附加權責於物件身上
Composite -down-> Flyweight:共享複合體
Composite ---up-> Iterator:列舉組件

Interpreter ---up-> Composite:定義文法
Interpreter ---left-> Flyweight:共享終端符號
Interpreter --right-> Visitor:增添操作
Visitor -up-> Iterator:定義巡訪方式
Visitor -[hidden]right- [Chain of Responsibility]
Iterator -up-> Memento:儲存巡訪狀態
Command -left-> Composite:由…所組成
Command -left->Memento:避免錯亂
State -up-> Flyweight:共享狀態
Strategy -right-> Flyweight:共享策略
Strategy <--left--> Decorator:改變內外

[Template Method] -[hidden]up- State
[Template Method] ---left-> Strategy:定義演算法步驟
[Template Method] -right-> [Factory Method]:常用到…
[Abstract Factory] -left-> Prototype:動態設定組態
[Abstract Factory] -up-> [Factory Method]:以它來實作
[Abstract Factory] -down-> Singleton:單一物件個體
Facade -left-> Singleton:單一物件個體
Observer -up-> Mediator:管理複雜的依存關係
[Chain of Responsibility] -[hidden]- Mediator

Adapter -[hidden]up- Proxy
Bridge -[hidden]up- Adapter
Memento -[hidden]right- Proxy
@enduml