// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace IOTGateway.Models
{
    public partial class TelemetryData
    {
        private string _aDSLor3G;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string ADSLor3G
        {
            get { return this._aDSLor3G; }
            set { this._aDSLor3G = value; }
        }
        
        private int? _dCorAC;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? DCorAC
        {
            get { return this._dCorAC; }
            set { this._dCorAC = value; }
        }
        
        private string _deviceId;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string DeviceId
        {
            get { return this._deviceId; }
            set { this._deviceId = value; }
        }
        
        private string _message;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Message
        {
            get { return this._message; }
            set { this._message = value; }
        }
        
        private string _seqNo;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string SeqNo
        {
            get { return this._seqNo; }
            set { this._seqNo = value; }
        }
        
        private int? _temperature;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? Temperature
        {
            get { return this._temperature; }
            set { this._temperature = value; }
        }
        
        private DateTimeOffset? _timestamp;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public DateTimeOffset? Timestamp
        {
            get { return this._timestamp; }
            set { this._timestamp = value; }
        }
        
        private int? _type;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? Type
        {
            get { return this._type; }
            set { this._type = value; }
        }
        
        private string _uID;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string UID
        {
            get { return this._uID; }
            set { this._uID = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the TelemetryData class.
        /// </summary>
        public TelemetryData()
        {
        }
        
        /// <summary>
        /// Serialize the object
        /// </summary>
        /// <returns>
        /// Returns the json model for the type TelemetryData
        /// </returns>
        public virtual JToken SerializeJson(JToken outputObject)
        {
            if (outputObject == null)
            {
                outputObject = new JObject();
            }
            if (this.ADSLor3G != null)
            {
                outputObject["ADSLor3G"] = this.ADSLor3G;
            }
            if (this.DCorAC != null)
            {
                outputObject["DCorAC"] = this.DCorAC.Value;
            }
            if (this.DeviceId != null)
            {
                outputObject["DeviceId"] = this.DeviceId;
            }
            if (this.Message != null)
            {
                outputObject["Message"] = this.Message;
            }
            if (this.SeqNo != null)
            {
                outputObject["SeqNo"] = this.SeqNo;
            }
            if (this.Temperature != null)
            {
                outputObject["Temperature"] = this.Temperature.Value;
            }
            if (this.Timestamp != null)
            {
                outputObject["Timestamp"] = this.Timestamp.Value;
            }
            if (this.Type != null)
            {
                outputObject["Type"] = this.Type.Value;
            }
            if (this.UID != null)
            {
                outputObject["UID"] = this.UID;
            }
            return outputObject;
        }
    }
}
